// src/components/inlineNavigation.tsx

export const InlineNavigationTSX = ({navigationList} : {navigationList:any[]}) => {

    return(
        <div
            style={{ display: "flex", flexDirection: "column", fontStyle: "italic" }}
        >
            {
                navigationList.map((value, index) => (
                    <a key={`${index}`} href={`${value.route}`}>
                        {value.title}
                    </a>
                ))
            }
        </div>
    )

}

// src/components/inlineNavigation.vue
<script setup lang="ts">

const props = defineProps<{
    pages: any[]
    // pages: {
    //     route: string,
    //     title: string,
    // }[]
}>();

console.log(props?.pages)

</script>

<template>
    <div style="display: flex; flex-direction: column; font-style:italic;">
        <template v-for="page in props.pages">
            <a :href=page.route >{{ page.title }}</a>
        </template>
    </div>
</template>
